#pragma once

#include <cstdint>
#include "enum.hpp"


namespace bt {

namespace att {

enum class Op : uint8_t {
	ERROR_RSP = 0x01,

	EXCHANGE_MTU_REQ = 0x02,
	EXCHANGE_MTU_RSP = 0x03,

	FIND_INFORMATION_REQ = 0X04,
	FIND_INFORMATION_RSP = 0X05,
	FIND_BYTYPEVALUE_REQ = 0X06,
	FIND_BYTYPEVALUE_RSP = 0x07,

	READ_BY_TYPE_REQ = 0x08,
	READ_BY_TYPE_RSP = 0x09,
	READ_REQ = 0X0A,
	READ_RSP = 0X0B,
	READ_BLOB_REQ = 0X0C,
	READ_BLOB_RSP = 0x0d,
	READ_BY_GROUP_TYPE_REQ = 0x10,
	READ_BY_GROUP_TYPE_RSP = 0x11,

	WRITE_REQ = 0x12,
	WRITE_RSP = 0X13,
	WRITE_CMD = 0X52,
	SIGNED_WRITE_CMD = 0xc2,

	// notification containing handle and value
	HANDLE_VALUE_NTF = 0x1B,
	// indication containing handle and value
	HANDLE_VALUE_IND = 0x1D,
	// confirmation for ATT_HANDLE_VALUE_IND
	HANDLE_VALUE_CFM = 0x1E,
};

} // namespace att

namespace gatt {

// attribute types
enum class Type : uint16_t {
	PRIMARY_SERVICE = 0x2800,
	SECONDARY_SERVICE = 0X2801,
	INCLUDE_SERVICE = 0x2802,
	CHARACTERISTIC = 0x2803,
	CHARACTERISTIC_EXTENDED_PROPERTIES = 0X2900,
	CHARACTERISTIC_USER_DESCRIPTION = 0X2901,
	CLIENT_CHARACTERISTIC_CONFIGURATION = 0X2902,
	SERVER_CHARACTERISTIC_CONFIGURATION = 0X2903,
	CHARACTERISTIC_PRESENTATION_FORMAT = 0X2904,
	CHARACTERISTIC_AGGREGATE_FORMAT = 0x2904,
};

// characteristic properties
enum class CharacteristicProperties : uint8_t {
	BROADCAST = 0x01,
	READ = 0x02,
	WRITE_WITHOUT_RESPONSE = 0x04,
	WRITE = 0x08,
	NOTIFY = 0x10,
	INDICATE = 0x20,
	AUTHENTHICATED_SIGNED_WRITES = 0x40,
	EXTENDED_PROPERTIES = 0x80
};
FLAGS_ENUM(CharacteristicProperties)

} // namespace gatt

} // namespace bt
